#!/usr/bin/env python3
"""
situation-board v1

A bounded local tool that reads manual note files and generates
a compact markdown board.
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent


def project_path(relative_path: str) -> Path:
    """Resolve a project-local path from the script directory."""
    return PROJECT_DIR / relative_path


def extract_bullets(content: str) -> list[str]:
    """
    Extract non-empty bullet items from markdown content.

    Accepts lines starting with '- ' or '* '.
    Returns list of bullet content (without the leading marker).
    """
    bullets = []
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("- "):
            bullet_text = stripped[2:].strip()
            if bullet_text:
                bullets.append(bullet_text)
        elif stripped.startswith("* "):
            bullet_text = stripped[2:].strip()
            if bullet_text:
                bullets.append(bullet_text)
    return bullets


def read_note_file(path: Path) -> list[str]:
    """
    Read a note file and extract bullet items.

    Returns empty list if file doesn't exist or is empty.
    """
    if not path.exists():
        return []

    try:
        content = path.read_text(encoding="utf-8")
        return extract_bullets(content)
    except Exception as e:
        print(f"Warning: Could not read {path}: {e}", file=sys.stderr)
        return []


def format_section(title: str, items: list[str]) -> str:
    """
    Format a board section with title and items.

    If items is empty, shows "(none)".
    """
    lines = [f"## {title}", ""]

    if not items:
        lines.append("(none)")
    else:
        for item in items:
            lines.append(f"- {item}")

    lines.append("")
    return "\n".join(lines)


def generate_board(inbox_items: list[str],
                   followup_items: list[str],
                   hold_items: list[str]) -> str:
    """
    Generate the situation board markdown.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    parts = [
        "# Situation Board",
        "",
        f"Generated: {timestamp}",
        "",
        "_This board reflects declared inputs only._",
        "",
        "---",
        "",
        format_section("Current attention", inbox_items),
        format_section("Follow-up", followup_items),
        format_section("Hold / Not now", hold_items),
        "---",
        "",
        "Generated by situation-board v1",
    ]

    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(
        description="Generate situation board from manual note files"
    )
    parser.add_argument(
        "--inbox",
        type=Path,
        default=project_path("notes/situation/inbox.md"),
        help="Path to inbox file (default: notes/situation/inbox.md)"
    )
    parser.add_argument(
        "--follow-ups",
        type=Path,
        default=project_path("notes/situation/follow-ups.md"),
        help="Path to follow-ups file (default: notes/situation/follow-ups.md)"
    )
    parser.add_argument(
        "--hold",
        type=Path,
        default=project_path("notes/situation/hold.md"),
        help="Path to hold file (default: notes/situation/hold.md)"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=project_path("notes/situation-board.md"),
        help="Path to output board (default: notes/situation-board.md)"
    )

    args = parser.parse_args()

    # Read input files
    inbox_items = read_note_file(args.inbox)
    followup_items = read_note_file(args.follow_ups)
    hold_items = read_note_file(args.hold)

    # Generate board
    board_content = generate_board(inbox_items, followup_items, hold_items)

    # Write output
    try:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(board_content, encoding="utf-8")
        print(f"Generated board at: {args.output}")
    except Exception as e:
        print(f"Error: Could not write board to {args.output}: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
